#!/usr/bin/env bash
# Prepare a local noReita copy and start PHP's development server.
set -euo pipefail

script_dir="$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)"
source_dir="$script_dir/noreita"
test_root="${NOREITA_TEST_DIR:-$HOME/dev/noReita.test}"
test_dir="$test_root/noreita"
host="${NOREITA_TEST_HOST:-127.0.0.1}"
port="${NOREITA_TEST_PORT:-8080}"
php_bin="${PHP_BIN:-php}"

if [[ ! -d "$source_dir" ]]; then
  echo "noReita source directory was not found: $source_dir" >&2
  exit 1
fi
if [[ ! "$port" =~ ^[1-9][0-9]{0,4}$ ]] || (( port > 65535 )); then
  echo "NOREITA_TEST_PORT must be a valid TCP port." >&2
  exit 1
fi
if ! command -v "$php_bin" >/dev/null 2>&1; then
  echo "PHP executable was not found: $php_bin" >&2
  exit 1
fi

mkdir -p "$test_root"
mkdir -p "$test_dir"

# Copy application files without source runtime data or source-local configuration.
tar -C "$source_dir" \
  --exclude='./config.local.php' \
  --exclude='./*.db' \
  --exclude='./*.db-*' \
  --exclude='./img' \
  --exclude='./thumbnail' \
  --exclude='./tmp' \
  --exclude='./cache' \
  --exclude='./session' \
  --exclude='./backup' \
  --exclude='./errorlog' \
  --exclude='./auditlog' \
  -cf - . | tar -C "$test_dir" -xf -

if [[ ! -f "$test_dir/config.local.php" ]]; then
  umask 077
  cat > "$test_dir/config.local.php" <<'PHP'
<?php
// Generated by pre.sh. This file is only for local development.
return [
  'admin' => [
    'password' => 'local-test-admin-password-change-me',
    'name' => 'ローカル管理人',
  ],
  'site' => [
    'base_url' => getenv('NOREITA_TEST_BASE_URL') ?: 'http://127.0.0.1:8080/',
    'title' => 'noReita ローカルテスト',
    'home_url' => './',
    'timezone' => 'Asia/Tokyo',
  ],
  'identity' => [
    'seed' => 'local-test-id-seed-change-me',
  ],
  'security' => [
    'paint_password' => 'local-test-paint-password-change-me',
    'session_name' => 'noreita_local_test_session',
  ],
];
PHP
else
  echo "Keeping existing local configuration: $test_dir/config.local.php"
fi

echo "Local test copy: $test_dir"
echo "Open: http://${host}:${port}/index.php"
echo "Administrator password: local-test-admin-password-change-me"
export NOREITA_TEST_BASE_URL="http://${host}:${port}/"
exec "$php_bin" -S "${host}:${port}" -t "$test_dir"
